# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_restaurant_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='owner',
        ),
    ]
