# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170620_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='version',
            name='version',
        ),
        migrations.AddField(
            model_name='version',
            name='versionCode',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='version',
            name='versionName',
            field=models.CharField(default='1.0.0', max_length=10),
        ),
    ]
