# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-12 02:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170627_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='star',
            name='comment',
        ),
    ]
