# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-18 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20170718_1622'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaruantMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=40, null=True)),
                ('longitude', models.CharField(max_length=40, null=True)),
                ('realDistance', models.FloatField(max_length=10, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Restaurant')),
            ],
        ),
    ]
